language: ruby
rvm:
- 2.3.1
deploy:
  provider: heroku
  api_key:
    secure: dHc5uWhHCx/Ig9NLx9NJqk/6Sc9d2kExpiuadFJ03NdpL1gWpZ3WXt8CBZJCUO/SJdDB15YN8b8UWCMZofSTSQyMhPiGPWElMGIyF1Zyxh7l5FZ8hQ672ODfU75WPf/iAZurtuxaAMwJWK5R0aljSCrbMGqLhA+PYxBH/UEF/jjBq3C/9dOSBs5zCW6KSu272XAZSWpLEoUOrnod/xhb0dSHUkQ4EEZvDjIUZ/TFOhZaoPF+q5F7pU3Z3qJzJxZhzLI8wbXZaVlwcpbJ/TdwgY1Y9L4PNmm8Ho1GNKUVXU4wJD9Nascvtz7HEva8inRTLZiVKOZUN1vjO5luSGzhx6+61FjepxciXVU45yIDIQah5KN3yU0E8PldwL1XeHQ/ghYg3ycgzCQRdUmc3JfnqDrRZZgRd8gucI6ZqYh5QUd11Bsjy+5fnoa+F1RdR4QIrUAXW+xg85dSAY+o0eah34O9tEPFL0b7tA8vCFD0f8NwI9/q1oEX+NGkVXFD+1LdhAyCYQtLaQC3uQkvb7EexEiI377F5o56nL4NMY7QzSHlc2/6LZjYx3UZuaSPerSOeFBvKhCWjnB1jupNwlVac5ZakkFF8Xm2onhYokcDm0eH6IF9HzQ9rhCn89C5DO3CjkQq8mn2c6M6wQGQQ9GGHj/ZMndX3uMSe/tjq9fdJ2E=
  app: limitless-tor-17231
  on:
    repo: Yzxwyydn/projet
